Vagrant.configure("2") do |config|
  config.vm.box = "Bensalah-hadoop"

  nodes = [
    { hostname: "NameNode", ip: "192.168.56.10", ports: { 50070 => 50070, 8088 => 8088, 9870 => 9870, 19888 => 19888 }},
    { hostname: "StandBy", ip: "192.168.56.13", ports: { 50070 => 50071, 8088 => 8089, 9870 => 9871, 19888 => 19889 }},
    { hostname: "DataNode1", ip: "192.168.56.11", ports: {}},
    { hostname: "DataNode2", ip: "192.168.56.12", ports: {}}
  ]

  # 1. Hardware Definition Loop
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.hostname = node[:hostname]
      node_config.vm.network "private_network", ip: node[:ip]
      
     node_config.vm.provider "virtualbox" do |vb|
        vb.name = "hadoop-cluster-#{node[:hostname]}"
        # BOTH NameNode and StandBy need 2GB
        if ["NameNode", "StandBy"].include?(node[:hostname])
          vb.memory = 2048
          vb.cpus = 2
        else
          vb.memory = 1024
          vb.cpus = 1
        end
      end

      node[:ports].each { |guest, host| node_config.vm.network "forwarded_port", guest: guest, host: host } 

      # TRIGGER PROVISIONING ONLY ON THE LAST NODE
      if node[:hostname] == "DataNode2"
        node_config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/playbook.yml" 
          ansible.inventory_path = "ansible/inventory.ini"
          ansible.limit = "all"
        end

        node_config.vm.provision "ansible", run: "always" do |ansible|
          ansible.playbook = "ansible/start_services.yml"
          ansible.inventory_path = "ansible/inventory.ini"
          ansible.limit = "NameNode,StandBy" 
        end
      end
    end
  end
end
