Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Configure resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # 1 GB RAM
    vb.cpus = 1         # 1 CPU
  end

  # Use Ansible to provision Java + Hadoop
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
end
